TRUNCATE TABLE pos_merchant_menus;
INSERT INTO `pos_merchant_menus` (`mer_menu_id`, `mer_menu_parent_id`, `mer_menu_index`, `mer_menu_text`, `mer_menu_class`, `mer_menu_url`) VALUES
(1, 0, 0, 'Dashboard', 'fa-dashboard', ''),
(2, 0, 1, 'Statistic', 'fa-bar-chart-o', 'statistic'),
(3, 0, 2, 'Sale & Finances', 'fa-shopping-bag', 'salefinances'),
(4, 0, 3, 'Clients', 'fa-user-circle-o', 'clients'),
(5, 0, 4, 'Management', 'fa-th-large', 'management'),
(6, 0, 5, 'Marketing', 'fa-star-o', 'marketing'),
(7, 0, 6, 'Webbuilder', 'fa-cogs', 'webbuilder'),
(8, 0, 7, 'Users', 'fa-users', 'users'),
(9, 0, 8, 'Setting', 'fa-cog', 'setting'),
(10, 3, 0, 'Schedule', '', 'schedule'),
(11, 3, 1, 'Booking', '', 'booking'),
(12, 3, 2, 'Payment', '', 'payment'),
(13, 3, 3, 'Order History', '', 'order-history'),
(14, 3, 4, 'Expenses', '', 'expenses'),
(15, 4, 0, 'Clients', '', 'clients'),
(16, 4, 1, 'Groups', '', 'groups'),
(17, 4, 2, 'Import', '', 'import'),
(18, 5, 1, 'Rent Stations', '', 'staffs'),
(19, 5, 3, 'Tax Forms', '', 'taxforms'),
(21, 6, 1, 'Reviews', '', 'reviews'),
(22, 6, 2, 'SMS/Email', '', 'sms'),
(23, 6, 3, 'Coupons', '', 'coupons'),
(24, 6, 4, 'Promotions', '', 'promotions'),
(25, 6, 5, 'Gift cards', '', 'giftcards'),
(26, 6, 6, 'Image Templates', '', 'contenttemplates'),
(27, 7, 1, 'Service Categories', '', 'cateservices'),
(28, 7, 2, 'Services', '', 'services'),
(29, 7, 3, 'Menus', '', 'menus'),
(30, 7, 4, 'Banners', '', 'banners'),
(31, 7, 5, 'Themes', '', 'themes'),
(32, 7, 6, 'Contacts', '', 'contacts'),
(33, 7, 7, 'Social Network', '', 'social-network'),
(34, 8, 1, 'Users', '', 'users'),
(35, 8, 2, 'Roles', '', 'roles'),
(36, 8, 3, 'Permission Setting', '', 'permissions'),
(37, 9, 1, 'Business Store', '', 'bstore'),
(38, 9, 2, 'System', '', 'system'),
(39, 5, 2, 'Attendances', '', 'staff-attendances'),
(40, 1, 0, 'Dashboard', '', 'dashboard'),
(41, 2, 1, 'Finance', '', 'finance'),
(42, 2, 2, 'Client', '', 'client'),
(43, 2, 3, 'Staff', '', 'staff'),
(44, 2, 4, 'Expense', '', 'expense');
